version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: gonza
      MYSQL_DATABASE: dbChallenge
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - my-network

  api:
    build: .
    container_name: api-Challenge
    ports:
      - "5000:5000"
    environment:
      DB_HOST: mysql-db
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: gonza
      DB_NAME: dbChallenge
    depends_on:
      - mysql
    networks:
      - my-network

networks:
  my-network:
    driver: bridge
